#define PROGRAM_FILE "kernel.cl"
#pragma warning(disable: 4996)
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include<time.h>
#include<math.h>
#include <sys/resource.h>
#include<string.h>
#ifdef MAC
#include <OpenCL/cl.h>
#else  
#include <CL/cl.h>
#endif

#define dg 256 

/* pat -> pattern
    txt -> text
    q -> A prime number
*/
void search(char* pat, char* txt, int q)
{
    int M = strlen(pat);
    //printf("\n\n%d \n",M);
    int N = strlen(txt);
    int i, j;
    int p = 0; // hash value for pattern 
    int t = 0; // hash value for txt 
    int h = 1;

    // The value of h would be "pow(d, M-1)%q" 
    for (i = 0; i < M - 1; i++)
        h = (h * dg) % q;

    // Calculate the hash value of pattern and first 
    // window of text 
    for (i = 0; i < M; i++)
    {
        p = (dg * p + pat[i]) % q;
        t = (dg * t + txt[i]) % q;
    }
    int g = 0;
    //printf("%d %d rty\n", t,p);
    // Slide the pattern over text one by one 
    for (i = 0; i <= N - M; i++)
    {

        // Check the hash values of current window of text 
        // and pattern. If the hash values match then only 
        // check for characters on by one 
        if (p == t)
        {
            /* Check for characters one by one */
            for (j = 0; j < M; j++)
            {
                if (txt[i + j] != pat[j])
                    break;
            }

            // if p == t and pat[0...M-1] = txt[i, i+1, ...i+M-1] 
             if (j == M)
                 printf("pos:%d  ", i);
        }

        // Calculate hash value for next window of text: Remove 
        // leading digit, add trailing digit 
        if (i < N - M)
        {
            int hjk = t;
            t = (dg * (t - txt[i] * h) + txt[i + M]) % q;
            

            // We might get negative value of t, converting it 
            // to positive 
            if (t < 0)
                t = (t + q);
            
            
        }
    }
}


int main() {

const rlim_t kStackSize = 1024L * 1024L * 1024L;   // min stack size = 64 Mb
    struct rlimit rl;
    int stack_result;

    stack_result = getrlimit(RLIMIT_STACK, &rl);
    if (stack_result == 0)
    {
        if (rl.rlim_cur < kStackSize)
        {
            rl.rlim_cur = kStackSize;
            stack_result = setrlimit(RLIMIT_STACK, &rl);
            if (stack_result != 0)
            {
                fprintf(stderr, "setrlimit returned result = %d\n", stack_result);
            }
        }
    }
double avg_squential=0;
double avg_parallel=0;

    for (int yu=0;yu<10;yu++){
    cl_platform_id platform;
    cl_device_id device;
    cl_context context;
    cl_command_queue queue;
    cl_int  err;

    
    cl_program program;
    FILE* program_handle;
    char* program_buffer, * program_log;
    size_t program_size, log_size;
    cl_kernel kernel;

    
    cl_mem mat_buff, vec_buff, res_buff;
    size_t work_units_per_kernel;

    cl_mem            m_dPingArray;
    cl_mem            m_string1;
    cl_mem            m_hash;
    cl_mem            m_string2;
    cl_mem            m_row;
    cl_mem            m_column;
    cl_mem            m_max_row;
    cl_mem            m_max_column;
    cl_mem            sub_buffer;
    cl_mem            m_test;
    cl_mem            m_indicate;
    cl_kernel         findHashes;
    cl_kernel         seekPattern;
    size_t            m_N;
    size_t            m_N_padded;
    //char b[20001] = "HelloTodayIsSundayAmSoHappyFoosundayHelloTodayIsSundayAmSoHappyFooHelloTodayIsSundayAmSoHappyFooSoHappyFoosundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdayHelloTodayIsSundayAmSoHappyFoosundayHelloTodayIsSundayAmSoHappyFooHelloTodayIsSundayAmSoHappyFooSoHappyFoosundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdayHelloTodayIsSundayAmSoHappyFoosundayHelloTodayIsSundayAmSosaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundsaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundsaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundsaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundsaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysatuHappyFooHelloTodayIsSundayAmSoHappyFooSoHappyFoosundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdayHelloTodayIsSundayAmSoHappyFoosundayHelloTodayIsSundayAmSoHappyFooHelloTodayIsSundayAmSoHappyFooSoHappyFoosundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysudaysundaysundaysundaysundaysundaysundaysundaysundaysndaysundaysundaysundaysundaysundaysundaysundaysundayundaysundaysundaysundaysundaysundaysundaysundaysundasundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysatu";
    //char a[20001] = "HelloTodayIsSundayAmSoHappyFoosundayHelloTodayIsSundayAmSoHappyFooHelloTodayIsSundayAmSoHappyFooSoHappyFoosundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdayHelloTodayIsSundayAmSoHappyFoosundayHelloTodayIsSundayAmSoHappyFooHelloTodayIsSundayAmSoHappyFooSoHappyFoosundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdayHelloTodayIsSundayAmSoHappyFoosundayHelloTodayIsSundayAmSosaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundsaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundsaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundsaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundsaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysatuHappyFooHelloTodayIsSundayAmSoHappyFooSoHappyFoosundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdayHelloTodayIsSundayAmSoHappyFoosundayHelloTodayIsSundayAmSoHappyFooHelloTodayIsSundayAmSoHappyFooSoHappyFoosundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysudaysundaysundaysundaysundaysundaysundaysundaysundaysndaysundaysundaysundaysundaysundaysundaysundaysundayundaysundaysundaysundaysundaysundaysundaysundaysundasundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysundaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysaturdaysatu";
    ////cl_uint im[t];
    //long int str1len = strlen(a);
    //long int str2len = strlen(b);
    //printf("%d %d\n", str1len, str2len);

    FILE* infile1, * infile2;
    char* a, * b;
    long sizea, sizeb;

    infile1 = fopen("1million.txt", "r");
    infile2 = fopen("pattern.txt", "r");

    if (infile1 == NULL) {
        printf("File Not Found!\n");
        return -1;
    }
    if (infile2 == NULL) {
        printf("File Not Found!\n");
        return -1;
    }

    fseek(infile1, 0L, SEEK_END);
    sizea = ftell(infile1);
    //sizea = 102176;
    fseek(infile2, 0L, SEEK_END);
    sizeb = ftell(infile2);
    //printf("%d %d 156", sizea,sizeb);
    fseek(infile1, 0L, SEEK_SET);
    fseek(infile2, 0L, SEEK_SET);

    a = (char*)calloc(sizea, sizeof(char));
    b = (char*)calloc(sizeb, sizeof(char));

    if (a == NULL)
        return 1;


    int return_val = fread(a, sizeof(char), sizea, infile1);
    fclose(infile1);

    fread(b, sizeof(char), sizeb, infile2);
    fclose(infile2);

    long int str1len = strlen(a);
    
    long int str2len = strlen(b);

    a[str1len] = '\0';
    b[sizeb] = '\0';

    str1len = strlen(a);
    
    str2len = strlen(b);
    

    int d = 256;
    int q = 50000;
    int num_cores = 256;
    int str_length = strlen(a);
    //int nElem=str_length;
    int pattern_length = strlen(b);
    int chunk_len = (int)ceil((float)str_length / num_cores);
    int padding_len = chunk_len * num_cores - str_length;
    int el_chunk_len = chunk_len + pattern_length - 1;


    int* seq_hash = malloc(sizeof(int) * num_cores * chunk_len);
    //CHECK(cudaDeviceReset());
    clock_t bn = clock();
    clock_t enk;
    search(b, a, q);
    enk = clock();
    double time_sp = 0.0;
    time_sp = time_sp + (double)(enk - bn) / CLOCKS_PER_SEC;
    printf("sequential total time %f for text lenght : %d and pattern lenght : %d \n", time_sp, str1len, str2len);
    //printf("%d %d %d seq_hassh\n", seq_hash[0], seq_hash[1], seq_hash[2]);
    avg_squential=avg_squential+time_sp;


    cl_uint hash[num_cores][el_chunk_len];

    cl_int result[num_cores][el_chunk_len];
    
    //matrix on host which holds the characters, each row will go to a core
    char css[num_cores][el_chunk_len];
    int iss[num_cores][el_chunk_len];
    //on the device
    char* d_css;
    char* d_pattern;
    int i = 0;
    int j = 0;
    //hashes on the device
    int* d_iss;
    int nchars = num_cores * el_chunk_len;

    for (i = 0; i < pattern_length - 1; i++)
        css[0][i] = 0;

    //first n-1 cores' characters
    for (i = 0; i < num_cores - 1; i++)
        for (j = 0; j < chunk_len; j++)
            css[i][j + pattern_length - 1] = a[i * chunk_len + j];

    //last core's characters
    for (i = (num_cores - 1) * chunk_len, j = 0; i < str_length; i++, j++)
        css[num_cores - 1][j + pattern_length - 1] = a[i];
    //printf("i=1 value\n");
    //int firs = 0;
    //last n-1 cores' padding characters
    for (i = 1; i < num_cores; i++)
    {
        for (j = 0; j < pattern_length - 1; j++) {
            css[i][j] = css[i - 1][j + chunk_len];
       
        }
        
}
    //firs = (dg * firs + css[1][pattern_length-1]) % q;
    //printf("\n firs:%d \n",firs);
    //last core's last paddings
    for (i = 0; i < padding_len; i++)
        css[num_cores - 1][el_chunk_len - i - 1] = 0;
    int p = 1;
    
    for (i = 0; i < pattern_length - 1; i++)
        p = (p * dg) % q;
    //int p = pow(d, pattern_length - 1);
    printf("%d %d %d \n", p, el_chunk_len, pattern_length);
    //printf("%d %d %c abg\n", strlen(a), strlen(b),a[0]);
    printf("hkdvkh\n");

    clock_t begin;// = clock();
    clock_t end;
    /* Identify a platform */
    err = clGetPlatformIDs(1, &platform, NULL);
    if (err < 0) {
        perror("Couldn't find any platforms");
        exit(1);
    }

    /* Access a device */
    err = clGetDeviceIDs(platform, CL_DEVICE_TYPE_GPU, 1, &device, NULL);
    if (err < 0) {
        perror("Couldn't find any devices");
        exit(1);
    }

    /* Create the context */
    context = clCreateContext(NULL, 1, &device, NULL, NULL, &err);
    if (err < 0) {
        perror("Couldn't create a context");
        exit(1);
    }

    /* Read program file and place content into buffer */
    program_handle = fopen(PROGRAM_FILE, "rb");
    if (program_handle == NULL) {
        perror("Couldn't find the program file");
        exit(1);
    }
    fseek(program_handle, 0, SEEK_END);
    program_size = ftell(program_handle);
    rewind(program_handle);
    program_buffer = (char*)malloc(program_size + 1);
    program_buffer[program_size] = '\0';
    fread(program_buffer, sizeof(char), program_size, program_handle);
    fclose(program_handle);

    /* Create program from file */
    program = clCreateProgramWithSource(context, 1,
        (const char**)&program_buffer, &program_size, &err);
    if (err < 0) {
        perror("Couldn't create the program");
        exit(1);
    }
    free(program_buffer);

    /* Build program */
    err = clBuildProgram(program, 0, NULL, NULL, NULL, NULL);
    if (err < 0) {

        /* Find size of log and print to std output */
        clGetProgramBuildInfo(program, device, CL_PROGRAM_BUILD_LOG,
            0, NULL, &log_size);
        program_log = (char*)malloc(log_size + 1);
        program_log[log_size] = '\0';
        clGetProgramBuildInfo(program, device, CL_PROGRAM_BUILD_LOG,
            log_size + 1, program_log, NULL);
        printf("%s\n", program_log);
        free(program_log);
        exit(1);
    }
    cl_mem m_el_chunk_len;
    cl_mem m_pattern_len;
    cl_mem m_d_pattern;
    cl_mem m_d;
    cl_mem m_p;
    //cl_mem m_result;
    cl_int clError, clError2;
    m_dPingArray = clCreateBuffer(context, CL_MEM_READ_WRITE, sizeof(char) * (num_cores) * (el_chunk_len), NULL, &clError2);
    clError = clError2;
    m_hash = clCreateBuffer(context, CL_MEM_READ_WRITE, sizeof(cl_uint) * (num_cores) * (el_chunk_len), NULL, &clError2);
    clError |= clError2;
    m_el_chunk_len = clCreateBuffer(context, CL_MEM_READ_WRITE, sizeof(cl_uint) * 1, NULL, &clError2);
    clError |= clError2;
    m_pattern_len = clCreateBuffer(context, CL_MEM_READ_WRITE, sizeof(cl_uint) * 1, NULL, &clError2);
    clError |= clError2;
    m_d_pattern = clCreateBuffer(context, CL_MEM_READ_WRITE, sizeof(char) * sizeb, NULL, &clError2);
    clError |= clError2;
    m_d = clCreateBuffer(context, CL_MEM_READ_WRITE, 1 * sizeof(cl_uint), NULL, &clError2);
    clError |= clError2;
    m_p = clCreateBuffer(context, CL_MEM_READ_WRITE, 1 * sizeof(cl_uint), NULL, &clError2);
    clError |= clError2;
    //m_result = clCreateBuffer(context, CL_MEM_READ_WRITE, sizeof(cl_int) * (num_cores) * (el_chunk_len), NULL, &clError2);
    //clError |= clError2;

    if (clError < 0) {
        printf("pm %d", clError);
        exit(1);
    }

    queue = clCreateCommandQueue(context, device, 0, &err);
    if (err < 0) {
        perror("Couldn't create the command queue");
        exit(1);
    }

    findHashes = clCreateKernel(program, "findHashes", &clError);
    if (clError < 0) {
        printf("qweer %d", clError);
        exit(1);
    }

    seekPattern = clCreateKernel(program, "seekPattern", &clError);
    if (clError < 0) {
        printf("qweer %d", clError);
        exit(1);
    }

    size_t globalWorkSize[1];
    size_t localWorkSize[1];

//arguments for the findhashes function which works on gpu .
    clError = clSetKernelArg(findHashes, 0, sizeof(cl_mem), (void*)&m_dPingArray);

    clError |= clSetKernelArg(findHashes, 1, sizeof(cl_mem), (void*)&m_hash);
    clError |= clSetKernelArg(findHashes, 2, sizeof(cl_uint), (void*)&el_chunk_len);
    clError |= clSetKernelArg(findHashes, 3, sizeof(cl_uint), (void*)&pattern_length);
    
    clError |= clSetKernelArg(findHashes, 4, sizeof(cl_uint), (void*)&d);
    clError |= clSetKernelArg(findHashes, 5, sizeof(cl_uint), (void*)&p);
    clError |= clSetKernelArg(findHashes, 6, sizeof(cl_uint), (void*)&q);
    
    if (clError < 0) {
        printf("op %d", clError);
        exit(1);
    }

    clEnqueueWriteBuffer(queue, m_d_pattern, CL_FALSE, 0, sizeb * sizeof(char), b, 0, NULL, NULL);
    clEnqueueWriteBuffer(queue, m_dPingArray, CL_FALSE, 0, (num_cores) * (el_chunk_len) * sizeof(char), css[0], 0, NULL, NULL);
    

    globalWorkSize[0] = num_cores;
    localWorkSize[0] = num_cores;
    begin = clock();
    //call to parallel funtion findhash which is used to find the hash value of the text.
    clError = clEnqueueNDRangeKernel(queue, findHashes, 1, NULL, globalWorkSize, localWorkSize, 0, NULL, NULL);
    if (clError < 0)
    {
        perror("Couldn't enqueue the kernel execution command");
        exit(1);
    }
    

    int p0 = 0;
    for (i = 0; i < pattern_length; i++) {
        
        p0 = (dg * p0 + b[i]) % q;
        
    }
//arguments for the seekpattern function which works on gpu .
    clError = clSetKernelArg(seekPattern, 0, sizeof(cl_mem), (void*)&m_dPingArray);

    clError |= clSetKernelArg(seekPattern, 1, sizeof(cl_mem), (void*)&m_hash);
    clError |= clSetKernelArg(seekPattern, 2, sizeof(cl_uint), (void*)&el_chunk_len);
    clError |= clSetKernelArg(seekPattern, 3, sizeof(cl_uint), (void*)&pattern_length);
    clError |= clSetKernelArg(seekPattern, 4, sizeof(cl_mem), (void*)&m_d_pattern);
     clError |= clSetKernelArg(seekPattern, 5, sizeof(cl_uint), (void*)&p0);
    //clError |= clSetKernelArg(seekPattern, 6, sizeof(cl_mem), (void*)&m_result);
 
    if (clError < 0) {
        printf("op %d", clError);
        exit(1);
    }  
//call to the parallel funtion seekpattern which is used to search for the pattern.
    clError = clEnqueueNDRangeKernel(queue, seekPattern, 1, NULL, globalWorkSize, localWorkSize, 0, NULL, NULL);

    end = clock();
    double time_spent = 0.0;
    time_spent = time_spent + (double)(end - begin) / CLOCKS_PER_SEC;
    printf("parallel total time %f for text lenght : %ld and pattern lenght : %ld \n", time_spent, str1len, str2len);
    printf("%f %f \n",avg_parallel,avg_squential);
    avg_parallel=avg_parallel+time_spent;
    
    clReleaseMemObject(m_dPingArray);
    clReleaseMemObject(m_hash);
    clReleaseMemObject(m_el_chunk_len);
    clReleaseMemObject(m_d);
    clReleaseMemObject(m_p);
    clReleaseKernel(findHashes);
    clReleaseProgram(program);
    clReleaseContext(context);
    clReleaseCommandQueue(queue);
}
avg_squential=avg_squential/10;
avg_parallel=avg_parallel/10;
 printf("avg sequential total time %f  \n", avg_squential);
 printf("avg parallel total time %f  \n", avg_parallel);
}